language: node_js
node_js: stable
services:
- postgresql
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
deploy:
  provider: heroku
  app: webcolors-api-staging
  on:
    repo: chubbystrings/web-colors_api
  skip_cleanup: true
  api_key:
    secure: Zg4v1rA2T3xwKjuPhBSJRnRIymZsx2jHnTaK0guLnbG9hJYed8rACyhKm+57Ui5SePZFU4iMqFjRbdgimIXPBqwya49NCcVO/zUN6n3iY5op9UX+lr2o5wKx3L648eJHITnJeuykMcSgf9bm7UsIqvxSzw8aBEsuD6nZQkE4hExLJHrNwmvKA27v+4RaRcerqe+XWO7wUBj09Qkvx3d0/qCan9B0V5qfgl2pgCvXDN7m6A9Myu/DzRk9LJEG9EDtxdhtgPKOqNgpyiMiwIT5p3u6isJ2wRQlW8ALTX5LKhTtpWI2qHoIXf2lEmI+CfBKuqDfObuJZNcgY4jv5M9mWQb8h0y0Z4FZ1Oljq8EmVlEvibZmP9082n3Jpb+G/IQKd1AAw51n9au255U/OPAPtIZ+ul6HFO1DwMc8ppNXqF1XcuFLCWcsEOGR7VefTR2os0mepsLOS8ByvWHWHszg7fLhvAwFShrOPBZWaOR+e2D3pgrDt+iRcGWlwKnFs97YdMlDSdVE9VF94fMv4Pe8EFNHWg6Z7GoTThkihTKqdjr+OHSsp7Pt72oxeA7rhMOpzp2Clp1vcJnn7ezPczgTEqle7CIeZI36Y+7RXb35vqaW3oNCJwrvGvyqm1DXLnSUGyCHB9IIoBDq90MyOMERjpzACLiOFXexhkeP52bx2jk=
install:
- npm install
script:
- npm test
env:
  global:
    secure: dSTQh72O/t+r4YdzJP1O5a2A6XNvaLyDMQTY1A5z41umAWPArpIZruJhije7P8vCHgKPV6lb/4bNpdNaBxHkJPsmJSg+KsutSb48sQtDLmd+pGug3OK3wSlqNriL0Sy1+WK4Sq0SJcFOBuVSagmdrQlzSsimT4xMO599n1Na6OStHo4Hnoh3/RnSn8tYIVXzid/YJiwLOsnONR6+7499zDxcUSN4CKkQ3Eix06tj+oUXdDc5p94DguCOpeLtwhjRg5UI3cUA7HpsNzEY9NPUOXq5gHM6oqOQvKJ+7fREblNhIc/b9g02tVxeDGqy3gRZwI+RekwTopF24YqUY6IvOAMovRcbxSfeXlQxrj7hKtASVtwJrCcywAqtXEPqZ7aT5eSv3GLNPU8DnF7kHuFpyNXeSvMibVTfQjN9iAm0db/Rqjo7Stkpy7CfLnbB3iU9UOOWh5CefmiPbc8rS48jChpzl6O3AClBN6XIFIaAuxhNs8dM4/7/grME67/LQ1iz5wUtg0SeJLDA+uQBYtsSzd+/Cyi5QC3K7oQUILB4sZbwled2e36iwBIxkbZqkVQJC6F2gdaBKr8SrhQ8ZD2Bd53geNjfJpBNfJ5mchIkC7JLbw/P7907EyqGUMCwvK+tNJx7dt3CFvQ2SaUazVfn66BMCCJUaiGvMFBdyWyW7A4=